### ISSUE TITLE
RTNETLINK answers: Broken pipe

### ISSUE THREAD

**Issue by federista** [westonrobot/ugv_sdk#19]
I am trying to connect my USB CAN with Bunker. i received te following error after executing 
**sudo ip link set can0 up type can bitrate 500000**
Additional Information:
"ifconfig can0" gives me the following output
can0: flags=128<NOARP>  mtu 16
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 10  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

How can I solve this

**Comment by rdu-weston** [comment]
> I am trying to connect my USB CAN with Bunker. i received te following error after executing

Can you post a screenshot of the error?

**Comment by federista** [comment]
The issue is solved but i have another issue 
when I run 
roslaunch bunker_bringup bunker_robot_base.launch
The process dies

![Screenshot from 2022-09-20 14-44-23](https://user-images.githubusercontent.com/63880770/191261066-b4fcca7e-037a-4dcc-a2b3-a73b6e47c74c.png)

**Comment by federista** [comment]
After running the provided two launch files I have the interface to control the robot using teleop_keyboard. Using the given commands I can see the difference in linear and angular velocities by echoing the topic but the robot doesn't move.
![Screenshot from 2022-09-20 17-34-52](https://user-images.githubusercontent.com/63880770/191302192-5d49f5a5-8b5d-4027-adb3-a887640302da.png)

**Comment by rdu-weston** [comment]
It seems your CAN interface is still not working properly. If set up correctly, you should see a lot of can msgs printed out when you run "candump can0". May I know what hardware and OS are you using?

**Comment by federista** [comment]
I am using Nvidia Jetson nano 4GB with Ubuntu 18.04
For CAN interface with bunker i am using CAN to usb adapter from candle light. 
At the very start when i connected bunker with the adapter, it was showing me the error: RTNETLINK: Broken pipe, which was solved by changing the wires. 
Now that error is solved but neither can i move the robot nor can i see printed msgs after candump can0

**Comment by rdu-weston** [comment]
Can you try with an amd64 computer (your laptop or desktop) first? The Linux kernel on Jetson is a little different. If you don't see candump msgs, then CAN interface is still not working properly, even though you don't see the RTNETLINK error any more. If CAN is not working, anything else for sure won't work.

**Comment by federista** [comment]
Sorry if i ask very basic questiona as i am a newbie to this
By trying amd64 computer you mean i dont have to connect it to jetson( as i dont know its architecture) for the sake of testing
Just connect the adapter to some 5v and test it on my laptop operating system
Right?

**Comment by federista** [comment]
I have checked the CAN adapter with my laptop with the required architecture but still no progress with candump can0. Though it gives me some kind of output. Do you have any idea what might be the reason behind it? I don't know why it's unable to read the device as I have connected the adapter with Bunker 's 5V output. 
I appreciate you giving time and answering my doubts. Thank you
![Screenshot from 2022-09-21 09-33-52](https://user-images.githubusercontent.com/63880770/191443249-6d2af6f4-2825-4e82-857a-18daeabf3b48.png)

**Comment by rdu-weston** [comment]
> I have checked the CAN adapter with my laptop with the required architecture but still no progress with candump can0. Though it gives me some kind of output. Do you have any idea what might be the reason behind it? I don't know why it's unable to read the device as I have connected the adapter with Bunker 's 5V output. I appreciate you giving time and answering my doubts. Thank you ![Screenshot from 2022-09-21 09-33-52](https://user-images.githubusercontent.com/63880770/191443249-6d2af6f4-2825-4e82-857a-18daeabf3b48.png)

Have you followed these steps to setup the can adapter? https://github.com/westonrobot/ugv_sdk#setup-can-to-usb-adapter

**Comment by federista** [comment]
Yes 
![Screenshot from 2022-09-21 10-20-39](https://user-images.githubusercontent.com/63880770/191453457-be8e49d4-7f86-4d72-a3e5-3f96cbcba381.png)

**Comment by rdu-weston** [comment]
> Yes ![Screenshot from 2022-09-21 10-20-39](https://user-images.githubusercontent.com/63880770/191453457-be8e49d4-7f86-4d72-a3e5-3f96cbcba381.png)

It seems the can adapter is brought up properly. Can you send me a photo showing how you connect the adapter to the robot?

**Comment by federista** [comment]
![1663749219108](https://user-images.githubusercontent.com/63880770/191456383-915fa2ca-d564-4288-8e0f-f63455ea9e78.jpg)

**Comment by federista** [comment]
Kindly let me know if below might be the reason for this issue
1) Do I need to install any sort of Driver for this USB-CAN adapter
2)How much is the importance of setting up slclan in the below manner
sudo ./slcan_attach -f -s5 -o /dev/ttyACM0
sudo ./slcand ttyACM0 slcan0
sudo ifconfig slcan0 up

**Comment by rdu-weston** [comment]
> Kindly let me know if below might be the reason for this issue
> 
>     1. Do I need to install any sort of Driver for this USB-CAN adapter
>        2)How much is the importance of setting up slclan in the below manner
>        sudo ./slcan_attach -f -s5 -o /dev/ttyACM0
>        sudo ./slcand ttyACM0 slcan0
>        sudo ifconfig slcan0 up

Following instructions at https://github.com/westonrobot/ugv_sdk#setup-can-to-usb-adapter would be sufficient.

The adapter relies on a kernel driver and "sudo modprobe gs_usb" would load this module. Then after executing "sudo ip link set can0 up type can bitrate 500000", you should get can0 up. No need for any slcan configuration.

**Comment by federista** [comment]
The abovementioned has been done but still no improvement

**Comment by rdu-weston** [comment]
>  Its connected to a 5v supply from bunker

5V supply? The adapter should connect with the CAN H & L signal from the robot.

**Comment by rdu-weston** [comment]
> The abovementioned has been done but still no improvement

May I know where you're located? Please contact your local distributor to check whether it's hardware issue.

**Comment by federista** [comment]
![1663750674856](https://user-images.githubusercontent.com/63880770/191461869-1cc019c2-b986-4b00-ae9d-a1f7d5c59e8a.jpg)
By 5v means the voltage at the two connected wires is 5V
In the picture as you can see the two wires from Black Box must be CAN H&L. If not, let me know which one it is

**Comment by federista** [comment]
All the above issues have been solved. The H and L can wires have been correctly connected. candump can0 also publish messages. When I switch the transmitter to command mode by toggling the SWB switch to the top, it doesn't move the robot. Though I can see on my laptop that command changes the speed and direction of the motor but no actual movement has been seen. 
![Screenshot from 2022-09-21 12-22-01](https://user-images.githubusercontent.com/63880770/191480610-65c83922-863a-42c0-b9ae-51414b62fb40.png)
![Screenshot from 2022-09-20 17-34-52](https://user-images.githubusercontent.com/63880770/191480866-507814a4-7551-406e-8283-27cd16ee62b5.png)

**Comment by federista** [comment]
The issue was on the mecahnical side. Solved it
If someone has issue they can contact me

**Comment by federista** [comment]
The issue was with the adapter socket. There was a power loss so i had to reinstall the socket after examining it. Now everything is sorted
